### ISSUE TITLE
Could some one tell the detail of how to use?

### ISSUE THREAD

**Issue by tianlichunhong** [hqvv/openwrt-udns#3]
please show the step by step of how to use. Thank you!

**Comment by hqvv** [comment]
git clone https://github.com/hqvv/openwrt-udns.git package/openwrt-udns
make menuconfig  , select it in Network >> IP Addresses and Names

**Comment by tianlichunhong** [comment]
make menuconfig in Network >> IP Addresses and Names only has "udns-libs" and "udns-utils", no "openwrt-udns". select  "udns-libs" and "udns-utils",then save. But it does not work.

**Comment by hqvv** [comment]
try the latest commit

**Comment by tianlichunhong** [comment]
use the  latest commit, make menuconfig in Network >> IP Addresses and Names only "udns-utils", and "make package/shadowsocks-libev/compile V=99" success. Thank you so much!!

**Comment by tianlichunhong** [comment]
but when I install in router,it still not work. 

root@lede:~# opkg install udns-utils_0.4-1_mipsel_24kc.ipk
Installing udns-utils (0.4-1) to root...
Configuring udns-utils.
root@lede:~# opkg install shadowsocks-libev_3.0.4-1_mipsel_24kc.ipk
Upgrading shadowsocks-libev on root from 2.6.2-1 to 3.0.4-1...
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocks-libev:
 *      libudns *
 * opkg_install_cmd: Cannot install package shadowsocks-libev.
